### ISSUE TITLE
Grafana version (outdated)

### ISSUE THREAD

**Issue by Comradin** [Banno/graphite-setup#3]
Hi,

Grafana does not need any longer an elasticsearch instance for its dashboards. The software was completly rewritten and now uses either internal sqlite database or any configured database like mysql or postgres.

Greetings,
Marcus

**Comment by adamdecaf** [comment]
@Comradin It appears that there is a [branch of the grafana 2 upgrade](https://github.com/Banno/graphite-setup/compare/grafana-version-2) already. I'm not sure why it hasn't been PR'ed though. @nicgrayson Can we merge that into master?

**Comment by adamdecaf** [comment]
@Comradin So I just saw that @rubbish opened up an [upgrade PR](https://github.com/Banno/graphite-setup/pull/4). Does that seem to fix your issue?
